### ISSUE TITLE
Cant load the plugin

### ISSUE THREAD

**Issue by Swiftly123** [WhipDevelopment/CrashClaim#2]
Hello,

I just bought Crashclaim and when i restart my server it says

[[[[Server thread/ERROR]: Error occurred while enabling CrashClaim v1.0.14 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.setLoreComponents(Ljava/util/List;)V
at net.crashcraft.crashclaim.localization.Localization$ItemStackTemplate.build(Localization.java:707) ~[?:?]
at net.crashcraft.crashclaim.localization.Localization$ItemStackTemplate.<init>(Localization.java:668) ~[?:?]
at net.crashcraft.crashclaim.localization.Localization.<init>(Localization.java:589) ~[?:?]
at net.crashcraft.crashclaim.localization.Localization.<clinit>(Localization.java:51) ~[?:?]
at net.crashcraft.crashclaim.localization.LocalizationLoader.initialize(LocalizationLoader.java:31) ~[?:?]
at net.crashcraft.crashclaim.CrashClaim.onEnable(CrashClaim.java:90) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]]]]

I have crashpayment install.

If someone can help me! Should be great
Thanks

**Comment by Chasewhip8** [comment]
Hey sorry about the late response can you please join the support discord at https://whips.dev/discord/ where we can help you out.

**Comment by Chasewhip8** [comment]
But the issue here is spigot support is borked in the latest version,  a fix is in the works but for now, you should consider upgrading to paper, https://papermc.io/ it is a fork of \spigot with performance improvements and more.

**Comment by Chasewhip8** [comment]
Closed assuming issue fixed.
